[package]
name = "re-sort"
version = "0.1.0"
authors = ["Nathan Moreau <nathan.moreau@m4x.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.3.5"
termcolor = "1.1"
