name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
          
    - name: Install GNU make
      uses: crazy-max/ghaction-chocolatey@v1
      with:
        args: install make

    - name: Run make
      run: |
        md %GOBIN%
        make -e all tests install
      env:
        CARGO_BIN: C:\bin
        GOBIN: C:\bin
        
    - name: Upload artifacts
      uses: softprops/action-gh-release@v1
      with:
        files: C:\bin\*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
